apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: pocketnow-stage-cloudflared
resources:
  - cloudflared.yaml
secretGenerator:
  - name: cloudflare-blog-cert
    files:
      - tunnelsecrets/cert.pem
  - name: cloudflare-blog-creds
    files:
      - tunnelsecrets/TUNNEL_ID.json
configMapGenerator:
  - name: cloudflare-blog-configs
    files:
      - tunnelconfig/config.yaml
