apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: pocketnow-stage-cloudflared
resources:
  - cloudflared.yaml
secretGenerator:
  - name: cloudflare-blog-cert
    files:
      - secrets/cert.pem
  - name: cloudflare-blog-creds
    files:
      - secrets/395f1f03-b92c-4750-8de8-547ac715a4a7.json
configMapGenerator:
  - name: cloudflare-blog-configs
    files:
      - config/config.yaml
