apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: geocache-fe
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
    #secretGenerator:
    #  - name: db-user-pass
    #    envs:
    #      - .env.password
configMapGenerator:
  - name: config-fe
    literals:
      - SERVICEURL=geocache-be-service:8090
        #      - UN=james@clarkezone.net
        #      - URLold=https://pocket-shortner-stage.dev.clarkezone.dev/
        #      - URL=http://pb-service:8080
