apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: pocketnow-frontend
resources:
- deployment.yaml
- service.yaml
secretGenerator:
- name: db-user-pass
  envs:
  - .env.password
configMapGenerator:
- name: psconfig
  literals:
  - UN=james@clarkezone.net
  - HOST=http://pb-service:8080
