apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocache-backend
  labels:
    app: kustomize
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kustomize
  template:
    metadata:
      labels:
        app: kustomize
    spec:
      containers:
        - name: geocache-backend
          image: registry.hub.docker.com/clarkezone/geocache:v0.0.2
            #image: registry.dev.clarkezone.dev/geocache:latest
          args: ["geocachegrpcserver"]

          imagePullPolicy: Always
          ports:
            - containerPort: 8090
