apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: geocache-be
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: psconfig
    literals:
#      - UN=james@clarkezone.net
#      - URLold=https://pocket-shortner-stage.dev.clarkezone.dev/
#      - URL=http://pb-service:8080
