apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketnow-geoquery
  labels:
    app: kust
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kust
  template:
    metadata:
      labels:
        app: kust
    spec:
      containers:
        - name: pocketnow-geoquery
          image: registry.hub.docker.com/clarkezone/pocketnow:dotnet8-manual-arm64-2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: COSMOSDB_URL
              valueFrom:
                secretKeyRef:
                  name: pocketnowcosmossecrets
                  key: COSMOSDB_URL
            - name: COSMOSDB_KEY
              valueFrom:
                secretKeyRef:
                  name: pocketnowcosmossecrets
                  key: COSMOSDB_KEY
