apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketnow-frontend
  labels:
    app: kust
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kust
  template:
    metadata:
      labels:
        app: kust
    spec:
      containers:
        - name: pocketnow-frontend
          #image: registry.dev.clarkezone.dev/pocketnow:latest
          #image: registry.hub.docker.com/clarkezone/pocketnow:0.0.3
          image: registry.hub.docker.com/clarkezone/pocketnow:dotnet8-manual-arm64-2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SERVICEURL
              valueFrom:
                configMapKeyRef:
                  name: pocketnowconfig
                  key: SERVICEURL
            - name: NOWMODE
              valueFrom:
                configMapKeyRef:
                  name: pocketnowconfig
                  key: NOWMODE
