apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: pocketnow-frontend
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: pocketnowconfig
    literals:
      - SERVICEURL=http://geocache-be-service:8090
      - NOWMODE=TRUE
