apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocache-backend
  labels:
    app: kustomize
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kustomize
  template:
    metadata:
      labels:
        app: kustomize
    spec:
      containers:
        - name: geocache-backend
          image: registry.hub.docker.com/clarkezone/geocache:cosmosflags2
            #image: registry.dev.clarkezone.dev/geocache:latest
          args: ["geocachegrpcserver"]

          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: DBWRITEENABLED
              valueFrom:
                configMapKeyRef:
                  name: config-fe
                  key: WRITEENABLED
            - name: DBCOSMOSURL
              valueFrom:
                configMapKeyRef:
                  name: config-fe
                  key: COSMOSURL
            - name: DBCOSMOSKEY
              valueFrom:
                secretKeyRef:
                  name: cosmoskey
                  key: COSMOSKEY
