apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: geocache-be
resources:
  - deployment.yaml
  - service.yaml
secretGenerator:
  - name: cosmoskey
    envs:
      - .env.cosmoskey
configMapGenerator:
  - name: psconfig
    literals:
      - WRITEENABLED=true
      - COSMOSURL=https://pocketnow.documents.azure.com:443/
#      - UN=james@clarkezone.net
#      - URLold=https://pocket-shortner-stage.dev.clarkezone.dev/
#      - URL=http://pb-service:8080
