apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: pocketnow-geoquery
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
secretGenerator:
  - name: pocketnowcosmossecrets
    envs:
      - .cosmosdbsecrets.env
