apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketnow
commonLabels:
  app: pocketnow-db
resources:
- namespace.yaml
- deployment.yaml
- persistentvolumeclaim.yaml
- pb-service.yaml
- pb-ingress.yaml
