apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocketshortener
commonLabels:
  app: pocketshortener-db
resources:
- namespace.yaml
- pocketbasedeployment.yaml
- persistentvolumeclaim.yaml
- pb-service.yaml
- pb-ingress.yaml
